### ISSUE TITLE
bin - This interaction failed

### ISSUE THREAD

**Issue by enzofoucaud** [TopiSenpai/dgo-paginator#5]
![image](https://github.com/user-attachments/assets/a471b7ad-f92b-481c-bb81-5b8b247ae178)

**Comment by topi314** [comment]
this can happen for multiple reasons
but since you only posted a screenshot...
¯\\_(ツ)_/¯

**Comment by enzofoucaud** [comment]
> this can happen for multiple reasons but since you only posted a screenshot... ¯\_(ツ)_/¯

the bug appears with the [example](https://github.com/topi314/dgo-paginator/blob/master/_examples/paginator/main.go)

**Comment by topi314** [comment]
unfortunately it seems like discordgo doesn't let you reset the components via a message update interaction response


this code generates: https://github.com/topi314/dgo-paginator/blob/master/paginator.go#L142
```json
[{"type":7,"data":{"tts":false,"content":"","components":[],"embeds":null}}]
```

while it should generate
```json
[{"type":7,"data":{"components":[]}}]
```

you're gonna have to take this up with discordgo maintainers since there is nothing I can fix here
